### ISSUE TITLE
"Module not found" on Windows when importing not from context dir

### ISSUE THREAD

**Issue by alex-bel** [goto-bus-stop/flat-loader#2]
How to reproduce:
1. PC or VM with Windows
2. unzip [example.zip](https://github.com/goto-bus-stop/flat-loader/files/870274/example.zip)
3. npm install
4. npm start
5. 
>  ERROR in ./src/app.js
> Module not found: Error: Can't resolve './stylesstyle.css' in 'c:\work\example\src'
>  @ ./src/app.js 2:0-39
>  @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js
> 

What happens: 
Substitution of external module at https://github.com/goto-bus-stop/flat-loader/blob/master/webpack-plugin.js#L86 uses relative path which, in case of Windows, results into ` import "./style\styles.css" ` emitted into output. Backslash(es) then get interpreted as escape characters, not as path separators.

Proposed fix:
Backslashes should be replaced with '/'.
In the webpack-plugin.js, replace
> return `${EXTERNAL_IDENTIFIER}./${relative.replace(/\.js$/, '')}`

with

> return `${EXTERNAL_IDENTIFIER}./${relative.replace(/\.js$/, '').replace(/\\/g, '/')}`

**Comment by goto-bus-stop** [comment]
Thanks for the detailed report! flat-loader v1.1.1 now converts all paths to use forward slashes before outputting them, so that should fix it :)

**Comment by alex-bel** [comment]
Thanks, 1.1.1 works fine for me
