### ISSUE TITLE
add support for jsx files

### ISSUE THREAD

**Issue by seeden** [goto-bus-stop/flat-loader#5]
I was not able to use it with jsx files.

**Comment by goto-bus-stop** [comment]
Yeah, Rollup doesn't support JSX--it needs another loader to transform JSX to valid ES6.

Something like

```js
module: {
  rules: [
    { include: path.join(__dirname, 'app.js'), use: 'flat-loader' },
    { test: /\.js$/, use: 'babel-loader' }
  ]
}
```

with a Babel config that transforms JSX, should work fine.

**Comment by goto-bus-stop** [comment]
Closing b/c it's _probably_ expected behaviour but if it isn't I don't know how to reproduce. I recommend using Webpack 3's ModuleConcatenationPlugin over this loader, it should solve any problems this one might have (eg. it works with bundle splitting)
